#!/bin/bash
echo "System Information"
echo "Executed By: $(whoami)"
echo "Hostname: $(hostname)"
echo "Server IP: $(hostname -I | awk '{print $1}')"
echo "Public IP: $(curl -s ifconfig.me)"
echo "OS Type and Version: $(lsb_release -d | cut -f2)"
echo "Kernel Version: $(uname -r)"
echo "Architecture: $(uname -m)"
echo "Virtualization: $(hostnamectl | grep Virtualization | cut -d ':' -f2)"
echo "Server Time: $(date)"
echo "Timezone: $(timedatectl | grep "Time zone" | awk '{print $3}')"
echo "Uptime: $(uptime -p)"
echo ""
echo "Resource Usage"
echo "Total Memory: $(free -h | grep Mem | awk '{print $2}')"
echo "Memory Usage: $(free -h | grep Mem | awk '{print $3 " / " $2}')"
echo "Swap Usage: $(free -h | grep Swap | awk '{print $3 " / " $2}')"
echo "CPU Cores: $(nproc)"
